server:
  port: 8083

spring:
  application:
    name: movie-service

  datasource:
    url: jdbc:postgresql://localhost:5432/movies_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
